name: Release
on:
  push:
#    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - run: sbt +sources
      - run: grep enrichAsJavaIntFunction target/scala-*/src_managed/main/FunctionConverters.scala
